### ISSUE TITLE
Unused socket

### ISSUE THREAD

**Issue by SylvainDeaure** [maccaspacca/Optipoolware#10]
https://github.com/maccaspacca/Optipoolware/blob/441a7b2a945a0d16c2fac4dc24a6d4bad2719f99/optipoolware.py#L558

Opening a socket to node that is never used anymore nor closed.

**Comment by maccaspacca** [comment]
Another left over from testnet. This should have been removed when I added the latest diff code. I will rectify

**Comment by maccaspacca** [comment]
Code commented out - I may be use again in later version.
