### ISSUE TITLE
Optimistic Hashrate

### ISSUE THREAD

**Issue by SylvainDeaure** [maccaspacca/Optipoolware#12]
https://github.com/maccaspacca/Optipoolware/blob/6f003b64fec38e57eae1cbdbde4411dd05dbd0e5/optihash.py#L79

This line should be above the array generation to account for the nonces generation time.
It's significant, and seems slower with more threads.

As it is, it's ok to test and optimize the hash part, but it does not give a correct value for the global hashrate of the miner.

**Comment by maccaspacca** [comment]
Yes, I have been thinking about that. However I suspect this is how acc-pool miner does the calculation based on the code that it was originally based on.

The reported hashrate drops by around 20% if I place the code before the nonce array creation - which is fine.

I tried multiple ways of creating the randomness and getrandbits is the fastest python way (except maybe secrets which is 3.6 only)

Let me give this some thought. In the meantime if you know of any ways of creating the randomness faster please let me know.

**Comment by maccaspacca** [comment]
I am looking at further improvements for optihash and I will include a rework of hash calculation at this time. The calculation will better reflect actual time mining.

**Comment by maccaspacca** [comment]
Fixed in latest commit for issue #14
